# Generated by Django 5.2.6 on 2025-10-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('NE', 'Mới 99-100%'), ('LN', 'Gần như mới (95-98%)'), ('US', 'Đã qua sử dụng (cũ hơn)')], default='US', max_length=2),
        ),
    ]
